# write a programm er the eight numbere by user and that are uniqye number and disple all the number 
s = set()
n =  input("enter the value  of numbert :  ")
s.add(int(n))
n =  input("enter the value  of numbert :  ")
s.add(int(n))
n =  input("enter the value  of numbert :  ")
s.add(int(n))
n =  input("enter the value  of numbert :  ")
s.add(int(n))
n =  input("enter the value  of numbert :  ")
s.add(int(n))
n =  input("enter the value  of numbert :  ")
s.add(int(n))
n =  input("enter the value  of numbert :  ")
s.add(int(n))
n =  input("enter the value  of numbert :  ")
s.add(int(n))
print(s)